### ISSUE TITLE
qt-vsaddin-msvc2022-x64-3.2.0-rev.47.vsix corrupt (please disregard this)

### ISSUE THREAD

**Issue by forderud** [qtproject/qt-labs-vstools#26]
I'm experiencing the following error when attempting to install the latest `qt-vsaddin-msvc2022-x64-3.2.0-rev.47.vsix`:  
![image](https://github.com/qt-labs/vstools/assets/2671400/96572dbc-c4e3-4b0a-90f6-770f22cb60f6)

Installation log:
```
10-Jun-24 10:36:43 AM - Microsoft VSIX Installer
10-Jun-24 10:36:43 AM - -------------------------------------------
10-Jun-24 10:36:43 AM - vsixinstaller.exe version:
10-Jun-24 10:36:43 AM - 17.8.2368+6fbeaa1954
10-Jun-24 10:36:43 AM - -------------------------------------------
10-Jun-24 10:36:43 AM - Command line parameters:
10-Jun-24 10:36:43 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\100030120\Downloads\qt-vsaddin-msvc2022-x64-3.2.0-rev.47.vsix
10-Jun-24 10:36:43 AM - -------------------------------------------
10-Jun-24 10:36:43 AM - Microsoft VSIX Installer
10-Jun-24 10:36:43 AM - -------------------------------------------
10-Jun-24 10:36:43 AM - Initializing Install...
10-Jun-24 10:36:43 AM - Searching for applicable products...
10-Jun-24 10:36:43 AM - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package. ---> System.IO.FileFormatException: File contains corrupted data.
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at VSIXInstaller.ExtensionEngineFactoryForSku.GetTypeFromEngine[TInterface](SupportedVSSKU sku, String typeName, Object[] constructorArguments)
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

### Steps to reproduce with manual download
1. Download "Qt Visual Studio Tools" from https://marketplace.visualstudio.com/items?itemName=TheQtCompany.QtVisualStudioTools2022 and double-click on the file.
2. Observe installation failure described above.

### Steps to reproduce from Visual Studio 2022
1. Select "Extensions" -> "Manage Extensions" -> "Online". Then search for "Qt Visual Studio Tools" and click "Download".
2. Observe that installation fail after approximately 25% with the following error:  
![image](https://github.com/qt-labs/vstools/assets/2671400/4bf38866-5e87-4c03-98b7-f34fa75029c9)

**Comment by forderud** [comment]
Please disregard this issue, since it was caused by a network configuration problem on my end that truncated downloaded files.
